theme: jekyll-theme-time-machine
title: "Save Madagascar"
description: "A charitable movement to improve the local quality of life in South Madagascar."
footerText: "It's time to stop talking about awareness and inspiration, it's time to do something! - Manoj Bhargava"
